LibraryProject/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryProject.Models.Entity;

namespace LibraryProject.Controllers
{
    public class KategoriController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLKATEGORI.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KategoriEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KategoriEkle(TBLKATEGORI p)
        {
            db.TBLKATEGORI.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult KategoriSil(int id)
        {
            var degerler = db.TBLKATEGORI.Find(id);
            db.TBLKATEGORI.Remove(degerler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var ktg = db.TBLKATEGORI.Find(id);
            return View("KategoriGetir", ktg);
        }
        public ActionResult KategoriGuncelle(TBLKATEGORI p)
        {
            var ktg = db.TBLKATEGORI.Find(p.ID);
            ktg.AD = p.AD;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LibraryProject/Views/Kategori/Index.cshtml
@using LibraryProject.Models.Entity
@model List<TBLKATEGORI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategoriler</h2>
<br />

<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Kategori Adı</th>
        <th>Durumu</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
            {
    <tr>
        <td>@item.ID</td>
        <td>@item.AD</td>
        <td><a href="/Kategori/KategoriSil/@item.ID" class="btn btn-outline-danger">Pasif Yap</a></td>
        <td><a href="/Kategori/KategoriGetir/@item.ID" class="btn btn-outline-warning">Güncelle</a></td>
       
    </tr>
            }
</table>

<a href="/Kategori/KategoriEkle" class="btn btn-outline-success">Kategori Ekle</a>
<br />
<br />

LibraryProject/Views/Kategori/KategoriEkle.cshtml
@model LibraryProject.Models.Entity.TBLKATEGORI
@{
    ViewBag.Title = "KategoriEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<p></p>

<form class="form-group" method="post">
    <div>
        <label>Kategori Adı</label>
        <div></div>
       <input type="text" class="form-control" name="AD" />
    </div>
    <div style="margin-top:15px">
        <a href="/Kategori/Index" class="btn btn-outline-success">Geri</a>
        <button class="btn btn-outline-primary">Kategori Ekle</button>
    </div>
</form>

LibraryProject/Views/Kategori/KategoriGetir.cshtml
@model LibraryProject.Models.Entity.TBLKATEGORI
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("KategoriGuncelle","Kategori",FormMethod.Post))
            {
    <div style="margin-bottom:15px"></div>
                <div class="form-group">
                    @Html.LabelFor(k=>k.ID)
                    @Html.TextBoxFor(k=>k.ID, new {@class="form-control"})
                    <br />
                    <b><h6>KATEGORİ ADI</h6></b>
                    @Html.TextBoxFor(k=>k.AD,new {@class="form-control"})
                </div>
                <br />
                <div>
                    <button class="btn btn-outline-warning">Güncelle</button>
                    <a href="/Kategori/Index/" class="btn btn-outline-dark">Geri</a>
                </div>
            }